config/routes.rb
Rails.application.routes.draw do
  root 'quizzes#index'

  get "/start_quiz", to: "quizzes#start"

  resources :quizzes do
    resources :questions, shallow: true

    get 'continue', on: :collection
    get 'completed', on: :collection
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :answer_text, presence: true

  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
    validates :question_text, presence: true
  
    belongs_to :quiz
    has_many :answers

    accepts_nested_attributes_for :answers, allow_destroy: true

    validates :question_text, presence: true
    validates_associated :answers
  end

app/models/quiz.rb
class Quiz < ApplicationRecord
  validates :title, presence: true, uniqueness: true

  before_validation :normalize_title

  before_save :normalize_description

  has_many :questions, dependent: :destroy

  protected

  def normalize_title
    Rails.logger.info("Quiz#normalize_title called")
    self.title = title.to_s.squish.capitalize
  end

  def normalize_description
    Rails.logger.info("Quiz#normalize_description called")
    self.description = description.to_s.squish
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_quiz, only: [:new, :create]

  def index
  end

  def create
    @question = @quiz.questions.new(question_params)

    @question.answers.new answer_text: params[:question][:answer1]
    @question.answers.new answer_text: params[:question][:answer2]
    @question.answers.new answer_text: params[:question][:answer3]




    if @question.save
      flash.notice = "Question was successfully created."
      redirect_to quiz_url(@quiz)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @question = @quiz.questions.new
    5.times { @question.answers.build } # Prepares 3 answer fields
  end

  def create
    @question = @quiz.questions.new(question_params)
    if @question.save
      flash.notice = "Jautājums veiksmīgi izveidots"
      redirect_to quiz_url(@quiz)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_quiz
    @quiz = Quiz.find(params[:quiz_id])
  end

  def question_params
    params.require(:question).permit(:question_text, answers_attributes: [:id, :answer_text, :correct, :_destroy])
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: %i[ show edit update destroy ]

  # GET /quizzes or /quizzes.json
  def index
    @quizzes = Quiz.all

    @title = 'These are the quizzes'
    @description = 'lorem ipsum'
  end

  def start
    @title = 'Start some quiz'
    @description = 'lorem ipsum'

    respond_to do |format|
      format.html
      format.json do
        render json: { title: @title, description: "Šī ir json atbilde" }
      end
    end
  end

  # GET /quizzes/1 or /quizzes/1.json
  def show
  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new
  end

  # GET /quizzes/1/edit
  def edit
  end

  # POST /quizzes or /quizzes.json
  def create
    @quiz = Quiz.new(quiz_params)

    respond_to do |format|
      if @quiz.save
        format.html do
          flash.notice = "Quiz was successfully created this time."
          redirect_to quiz_url(@quiz)
        end
        format.json { render :show, status: :created, location: @quiz }
      else
        flash.now.alert = 'Something went wrong'
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizzes/1 or /quizzes/1.json
  def update
    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to quiz_url(@quiz), notice: "Quiz was successfully updated." }
        format.json { render :show, status: :ok, location: @quiz }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1 or /quizzes/1.json
  def destroy
    @quiz.destroy!

    respond_to do |format|
      format.html { redirect_to quizzes_url, notice: "Quiz was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quiz_params
      params.require(:quiz).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def btn_class
      'inline-block rounded border border-indigo-600 bg-indigo-600 px-12 py-3 text-sm font-medium text-white hover:bg-transparent hover:text-indigo-600 focus:outline-none focus:ring active:text-indigo-500'
    end
  
    def format_date(date)
      date.strftime('%F')
    end
  end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/layouts/_notice.html.erb
<% flash.each do |type, message| %>
  <% if type == 'alert' %>
    <div role="alert" class="rounded border-s-4 border-red-500 bg-red-50 p-4">
      <strong class="block font-medium text-red-800"> <%= message %> </strong>
    </div>
  <% else %>
    <div role="alert" class="rounded border-s-4 border-lime-500 bg-lime-50 p-4">
      <strong class="block font-medium text-lime-800"> <%= message %> </strong>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quizzito</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body class="container mx-auto p-4">
    <%= render 'layouts/notice' %>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with(model: [question.quiz, question]) do |form| %>
  <% if question.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% question.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :question_text %>
    <%= form.text_field :question_text %>
  </div>

  <div>
    <%= form.label :answers, "Atbildes" %>
    <% question.answers.each_with_index do |answer, index| %>
     <div class="mt-2">
        <%= form.fields_for :answers, answer do |answer_form| %>
          <%= answer_form.label :answer_text, "Atbilde #{index + 1}" %>
          <%= answer_form.text_field :answer_text %>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="mt-4">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/create.html.erb
<h1>Questions#create</h1>
<p>Find me in app/views/questions/create.html.erb</p>

app/views/questions/index.html.erb
<h1>Questions#index</h1>
<p>Find me in app/views/questions/index.html.erb</p>

app/views/questions/new.html.erb
<h1><%= @quiz.title %></h1>
<h2>New question</h2>

<%= render "form", question: @question %>

<div class="mt-6">
  <%= link_to "Cancel", @quiz %>
</div>

app/views/questions/start.html.erb
<h1>Questions#start</h1>
<p>Find me in app/views/questions/start.html.erb</p>

app/views/questions/test.html.erb
<h1>Questions#test</h1>
<p>Find me in app/views/questions/test.html.erb</p>

app/views/quizzes/_form.html.erb
<%= form_with(model: quiz) do |form| %>
  <% if quiz.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
        <% quiz.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/quizzes/_quiz.html.erb
<div id="<%= dom_id quiz %>">
  <p>
    <strong>Title:</strong>
    <%= quiz.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= quiz.description %>
  </p>

  <h3>Questions</h3>
 <%= link_to 'Pievienot jautājumu', new_quiz_question_path(@quiz), class: "text-blue-500 hover:text-blue-700" %>
  
  <table id="quizzes" class="min-w-full divide-y-2 divide-gray-200 bg-white text-sm mt-4">
    <thead class="bg-gray-50">
      <tr>
        <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">Jautajums</th>
        <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">Atbilde</th>
        <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">Izveidots</th>
      </tr>
    </thead>
    <tbody class="divide-y divide-gray-200">
      <% quiz.questions.each do |question| %>
        <tr>
          <td class="whitespace-nowrap px-4 py-2 text-gray-900"><%= question.question_text %></td>
          <td class="whitespace-nowrap px-4 py-2 text-gray-900">
            <ul class="list-disc list-inside">
              <% question.answers.each do |answer| %>
                <li><%= answer.answer_text %></li>
              <% end %>
            </ul>
          </td>
          <td class="whitespace-nowrap px-4 py-2 text-gray-900 text-centre"><%= question.created_at.strftime("%B %d, %Y") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/quizzes/_quiz_row.html.erb
<tr>
  <td class="whitespace-nowrap px-4 py-2 font-medium text-gray-900"><%= quiz.id %></td>
  <td class="whitespace-nowrap px-4 py-2 text-gray-700"><%= quiz.title %></td>
  <td class="whitespace-nowrap px-4 py-2 text-gray-700"><%= quiz.description %></td>
  <td class="whitespace-nowrap px-4 py-2 text-gray-700"><%= format_date(quiz.created_at) %></td>
  <td class="whitespace-nowrap px-4 py-2 text-gray-700"><%= link_to("Open", quiz, class: 'inline-block rounded border border-indigo-600 px-4 py-1 text-sm font-medium text-indigo-600 hover:bg-indigo-600 hover:text-white focus:outline-none focus:ring active:bg-indigo-500') %></td>
</tr>

app/views/quizzes/edit.html.erb
<h1>Editing quiz</h1>

<%= render "form", quiz: @quiz %>

<br>

<div>
  <%= link_to "Show this quiz", @quiz %> |
  <%= link_to "Back to quizzes", quizzes_path %>
</div>

app/views/quizzes/index.html.erb
<h1><%= @title %></h1>
<p><%= @description %></p>

<div class="overflow-x-auto rounded-lg border border-gray-200">
  <table id="quizzes" class="min-w-full divide-y-2 divide-gray-200 bg-white text-sm">
    <thead class="text-left">
      <tr>
        <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">ID</th>
        <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">Nosaukums</th>
        <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">Apraksts</th>
        <th class="whitespace-nowrap px-4 py-2 font-medium text-gray-900">Izveidots</th>
      </tr>
    </thead>
    <tbody class="divide-y divide-gray-200">
      <%= render partial: 'quiz_row', collection: @quizzes, as: :quiz %>
    </tbody>
  </table>
</div>

<%= link_to "New quiz", new_quiz_path, class: btn_class %>

app/views/quizzes/new.html.erb
<h1>New quiz</h1>

<%= render "form", quiz: @quiz %>

<br>

<div>
  <%= link_to "Back to quizzes", quizzes_path %>
</div>

app/views/quizzes/show.html.erb
<%= render @quiz %>

<div>
  <%= link_to "Edit this quiz", edit_quiz_path(@quiz) %> |
  <%= link_to "Back to quizzes", quizzes_path %>

  <%= button_to "Destroy this quiz", @quiz, method: :delete %>
</div>

app/views/quizzes/start.html.erb
<h1><%= @title %></h1>
<p><%= @description %></p>